# Generated by Django 5.1.4 on 2025-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0002_candidate_email_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='username',
            field=models.CharField(default='Default User Name', max_length=100),
        ),
    ]
