# Generated by Django 5.1.4 on 2025-01-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0003_hr_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(default='Default User Name', max_length=100),
        ),
    ]
