# Generated by Django 5.1.4 on 2025-01-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0004_candidate_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', to='JRS.skill'),
        ),
    ]
