# Generated by Django 5.1.4 on 2025-01-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0006_alter_candidate_username_alter_hr_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='username',
        ),
    ]
