# Generated by Django 5.1.4 on 2025-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0008_candidate_username_hr_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
