# Generated by Django 5.1.4 on 2025-02-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='profile_picture',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pics/'),
        ),
    ]
