# Generated by Django 5.1.4 on 2025-02-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0011_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JRS.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JRS.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
