# Generated by Django 5.1.4 on 2025-02-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0012_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
    ]
