# Generated by Django 5.1.4 on 2025-03-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0013_jobapplication_cover_letter_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
