# Generated by Django 5.1.4 on 2025-03-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0014_candidate_confirmation_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='is_email_verified',
        ),
    ]
