# Generated by Django 5.1.4 on 2025-03-02 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0016_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
