# Generated by Django 5.1.4 on 2025-03-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0017_hr_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='verification_token',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
