# Generated by Django 5.1.4 on 2025-03-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0018_remove_hr_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
