# Generated by Django 5.1.4 on 2025-03-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0021_remove_hr_email_alter_hr_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
