# Generated by Django 5.1.4 on 2025-03-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0022_candidate_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('recommendation', models.CharField(max_length=50)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading', to='JRS.jobapplication')),
            ],
        ),
    ]
