# Generated by Django 5.1.4 on 2025-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0023_cvgrading'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
        ),
    ]
