# Generated by Django 5.1.4 on 2025-03-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0025_alter_jobapplication_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
