# Generated by Django 5.1.4 on 2025-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0026_jobapplication_is_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
