# Generated by Django 5.1.4 on 2025-03-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0037_jobapplication_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
