# Generated by Django 5.1.4 on 2025-04-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRS', '0039_remove_interviewfeedback_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='JRS.skill'),
        ),
    ]
